#GateWay And Nacos discovery  Nacos注册中心、数据源、端口号等配置
spring:
  cloud:
    gateway:
      routes:
        #Query A 参数有A就行，Query B,C 参数B的值为C即可
        #实现针对于“http://localhost:88/hello?url=baidu”，转发到“https://www.baidu.com/hello”，
        #针对于“http://localhost:88/hello?url=qq”的请求，转发到“https://www.qq.com/hello”
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/mallproduct/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
## 前端项目，/api 代api的都路由到renren_fast
#  http://localhost:88/api/captcha.jpg  转成  http://localhost:8080/renren-fast/captcha.jpg
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowCredentials: true
#            allowedHeaders: "*"
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            add-to-simple-url-handler-mapping: true
  application:
    name: mall-gateway
server:
  port: 88

#  nacos:
#    discovery:
#      server-addr: 127.0.0.1:8848